// Mocks generated by Mockito 5.0.17 from annotations
// in plante/test/common_mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;
import 'dart:io' as _i62;
import 'dart:typed_data' as _i20;

import 'package:flutter/material.dart' as _i61;
import 'package:flutter/services.dart' as _i65;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i43;
import 'package:google_maps_flutter_platform_interface/google_maps_flutter_platform_interface.dart'
    as _i4;
import 'package:http/http.dart' as _i35;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openfoodfacts/model/OcrIngredientsResult.dart' as _i6;
import 'package:openfoodfacts/openfoodfacts.dart' as _i5;
import 'package:openfoodfacts/utils/ProductListQueryConfiguration.dart' as _i49;
import 'package:plante/base/base.dart' as _i36;
import 'package:plante/base/general_error.dart' as _i72;
import 'package:plante/base/pair.dart' as _i52;
import 'package:plante/base/permissions_manager.dart' as _i59;
import 'package:plante/base/result.dart' as _i2;
import 'package:plante/base/size_int.dart' as _i64;
import 'package:plante/contributions/user_contribution.dart' as _i21;
import 'package:plante/contributions/user_contribution_type.dart' as _i22;
import 'package:plante/lang/sys_lang_code_holder.dart' as _i80;
import 'package:plante/lang/user_langs_manager.dart' as _i81;
import 'package:plante/lang/user_langs_manager_error.dart' as _i82;
import 'package:plante/location/geolocator_wrapper.dart' as _i40;
import 'package:plante/location/ip_location_provider.dart' as _i44;
import 'package:plante/location/user_location_manager.dart' as _i46;
import 'package:plante/model/coord.dart' as _i14;
import 'package:plante/model/coords_bounds.dart' as _i31;
import 'package:plante/model/lang_code.dart' as _i25;
import 'package:plante/model/product.dart' as _i38;
import 'package:plante/model/shop.dart' as _i12;
import 'package:plante/model/shop_product_range.dart' as _i75;
import 'package:plante/model/shop_type.dart' as _i76;
import 'package:plante/model/user_langs.dart' as _i7;
import 'package:plante/model/user_params.dart' as _i18;
import 'package:plante/model/user_params_controller.dart' as _i83;
import 'package:plante/model/veg_status.dart' as _i24;
import 'package:plante/outside/backend/backend.dart' as _i17;
import 'package:plante/outside/backend/backend_error.dart' as _i19;
import 'package:plante/outside/backend/backend_product.dart' as _i68;
import 'package:plante/outside/backend/backend_products_at_shop.dart' as _i27;
import 'package:plante/outside/backend/backend_response.dart' as _i3;
import 'package:plante/outside/backend/backend_shop.dart' as _i29;
import 'package:plante/outside/backend/mobile_app_config.dart' as _i26;
import 'package:plante/outside/backend/mobile_app_config_manager.dart' as _i47;
import 'package:plante/outside/backend/news/news_data_response.dart' as _i34;
import 'package:plante/outside/backend/product_at_shop_source.dart' as _i33;
import 'package:plante/outside/backend/product_presence_vote_result.dart'
    as _i32;
import 'package:plante/outside/backend/requested_products_result.dart' as _i23;
import 'package:plante/outside/backend/shops_in_bounds_response.dart' as _i30;
import 'package:plante/outside/backend/user_reports_maker.dart' as _i84;
import 'package:plante/outside/identity/apple_authorizer.dart' as _i15;
import 'package:plante/outside/identity/apple_user.dart' as _i16;
import 'package:plante/outside/identity/google_authorizer.dart' as _i41;
import 'package:plante/outside/identity/google_user.dart' as _i42;
import 'package:plante/outside/map/address_obtainer.dart' as _i8;
import 'package:plante/outside/map/directions_manager.dart' as _i39;
import 'package:plante/outside/map/osm/open_street_map.dart' as _i11;
import 'package:plante/outside/map/osm/osm_address.dart' as _i13;
import 'package:plante/outside/map/osm/osm_nominatim.dart' as _i53;
import 'package:plante/outside/map/osm/osm_overpass.dart' as _i55;
import 'package:plante/outside/map/osm/osm_road.dart' as _i57;
import 'package:plante/outside/map/osm/osm_search_result.dart' as _i54;
import 'package:plante/outside/map/osm/osm_searcher.dart' as _i58;
import 'package:plante/outside/map/osm/osm_shop.dart' as _i56;
import 'package:plante/outside/map/osm/osm_short_address.dart' as _i10;
import 'package:plante/outside/map/osm/osm_uid.dart' as _i28;
import 'package:plante/outside/map/roads_manager.dart' as _i70;
import 'package:plante/outside/map/shops_manager.dart' as _i73;
import 'package:plante/outside/map/shops_manager_types.dart' as _i74;
import 'package:plante/outside/off/off_api.dart' as _i48;
import 'package:plante/outside/off/off_shop.dart' as _i50;
import 'package:plante/outside/off/off_shops_manager.dart' as _i51;
import 'package:plante/products/contributed_by_user_products_storage.dart'
    as _i37;
import 'package:plante/products/products_manager.dart' as _i66;
import 'package:plante/products/products_manager_error.dart' as _i67;
import 'package:plante/products/products_obtainer.dart' as _i69;
import 'package:plante/products/suggestions/suggested_products_manager.dart'
    as _i77;
import 'package:plante/products/suggestions/suggestion_type.dart' as _i79;
import 'package:plante/products/suggestions/suggestions_for_shop.dart' as _i78;
import 'package:plante/products/viewed_products_storage.dart' as _i85;
import 'package:plante/ui/map/latest_camera_pos_storage.dart' as _i45;
import 'package:plante/ui/map/shop_creation/shops_creation_manager.dart'
    as _i71;
import 'package:plante/ui/photos/photo_requester.dart' as _i63;
import 'package:plante/ui/photos/photos_taker.dart' as _i60;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResult_0<OK, ERR> extends _i1.Fake implements _i2.Result<OK, ERR> {}

class _FakeBackendResponse_1 extends _i1.Fake implements _i3.BackendResponse {}

class _FakeLatLngBounds_2 extends _i1.Fake implements _i4.LatLngBounds {}

class _FakeScreenCoordinate_3 extends _i1.Fake implements _i4.ScreenCoordinate {
}

class _FakeLatLng_4 extends _i1.Fake implements _i4.LatLng {}

class _FakeSearchResult_5 extends _i1.Fake implements _i5.SearchResult {}

class _FakeStatus_6 extends _i1.Fake implements _i5.Status {}

class _FakeOcrIngredientsResult_7 extends _i1.Fake
    implements _i6.OcrIngredientsResult {}

class _FakeUserLangs_8 extends _i1.Fake implements _i7.UserLangs {}

/// A class which mocks [AddressObtainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressObtainer extends _i1.Mock implements _i8.AddressObtainer {
  MockAddressObtainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>
      addressOfShop(_i12.Shop? shop, {String? langCode}) => (super.noSuchMethod(
          Invocation.method(#addressOfShop, [shop], {#langCode: langCode}),
          returnValue:
              Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<_i10.OsmShortAddress, _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>);
  @override
  _i9.Future<_i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>> addressOfCoords(
          _i14.Coord? coords,
          {String? langCode}) =>
      (super.noSuchMethod(
          Invocation.method(#addressOfCoords, [coords], {#langCode: langCode}),
          returnValue: Future<
                  _i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>>.value(
              _FakeResult_0<_i13.OsmAddress, _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>>);
  @override
  _i9.Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>
      shortAddressOfCoords(_i14.Coord? coords) => (super.noSuchMethod(
          Invocation.method(#shortAddressOfCoords, [coords]),
          returnValue:
              Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<_i10.OsmShortAddress,
                      _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<_i10.OsmShortAddress, _i11.OpenStreetMapError>>);
}

/// A class which mocks [AppleAuthorizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleAuthorizer extends _i1.Mock implements _i15.AppleAuthorizer {
  MockAppleAuthorizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i16.AppleUser?> auth() =>
      (super.noSuchMethod(Invocation.method(#auth, []),
              returnValue: Future<_i16.AppleUser?>.value())
          as _i9.Future<_i16.AppleUser?>);
}

/// A class which mocks [Backend].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackend extends _i1.Mock implements _i17.Backend {
  MockBackend() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addObserver(_i17.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i17.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Result<_i18.UserParams, _i19.BackendError>> loginOrRegister(
          {String? googleIdToken, String? appleAuthorizationCode}) =>
      (super.noSuchMethod(
              Invocation.method(#loginOrRegister, [], {
                #googleIdToken: googleIdToken,
                #appleAuthorizationCode: appleAuthorizationCode
              }),
              returnValue:
                  Future<_i2.Result<_i18.UserParams, _i19.BackendError>>.value(
                      _FakeResult_0<_i18.UserParams, _i19.BackendError>()))
          as _i9.Future<_i2.Result<_i18.UserParams, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<bool, _i19.BackendError>> updateUserParams(
          _i18.UserParams? userParams,
          {String? backendClientTokenOverride}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUserParams, [userParams],
                  {#backendClientTokenOverride: backendClientTokenOverride}),
              returnValue: Future<_i2.Result<bool, _i19.BackendError>>.value(
                  _FakeResult_0<bool, _i19.BackendError>()))
          as _i9.Future<_i2.Result<bool, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<String, _i19.BackendError>> updateUserAvatar(
          _i20.Uint8List? avatarBytes) =>
      (super.noSuchMethod(Invocation.method(#updateUserAvatar, [avatarBytes]),
              returnValue: Future<_i2.Result<String, _i19.BackendError>>.value(
                  _FakeResult_0<String, _i19.BackendError>()))
          as _i9.Future<_i2.Result<String, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> deleteUserAvatar() =>
      (super.noSuchMethod(Invocation.method(#deleteUserAvatar, []),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  Uri? userAvatarUrl(_i18.UserParams? user) =>
      (super.noSuchMethod(Invocation.method(#userAvatarUrl, [user])) as Uri?);
  @override
  _i9.Future<_i2.Result<List<_i21.UserContribution>, _i19.BackendError>>
      requestUserContributions(
              int? limit, Iterable<_i22.UserContributionType>? types) =>
          (super.noSuchMethod(
                  Invocation.method(#requestUserContributions, [limit, types]),
                  returnValue:
                      Future<_i2.Result<List<_i21.UserContribution>, _i19.BackendError>>.value(
                          _FakeResult_0<List<_i21.UserContribution>, _i19.BackendError>()))
              as _i9.Future<
                  _i2.Result<List<_i21.UserContribution>, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i23.RequestedProductsResult, _i19.BackendError>>
      requestProducts(List<String>? barcodes, int? page) => (super.noSuchMethod(
          Invocation.method(#requestProducts, [barcodes, page]),
          returnValue: Future<_i2.Result<_i23.RequestedProductsResult, _i19.BackendError>>.value(
              _FakeResult_0<_i23.RequestedProductsResult,
                  _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i23.RequestedProductsResult, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> createUpdateProduct(
          String? barcode,
          {_i24.VegStatus? veganStatus,
          List<_i25.LangCode>? changedLangs}) =>
      (super.noSuchMethod(
          Invocation.method(#createUpdateProduct, [barcode],
              {#veganStatus: veganStatus, #changedLangs: changedLangs}),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> sendReport(
          String? barcode, String? reportText) =>
      (super.noSuchMethod(Invocation.method(#sendReport, [barcode, reportText]),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> sendProductScan(
          String? barcode) =>
      (super.noSuchMethod(Invocation.method(#sendProductScan, [barcode]),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i26.MobileAppConfig, _i19.BackendError>>
      mobileAppConfig() => (super.noSuchMethod(
          Invocation.method(#mobileAppConfig, []),
          returnValue: Future<
                  _i2.Result<_i26.MobileAppConfig, _i19.BackendError>>.value(
              _FakeResult_0<_i26.MobileAppConfig, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i26.MobileAppConfig, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<List<_i27.BackendProductsAtShop>, _i19.BackendError>>
      requestProductsAtShops(Iterable<_i28.OsmUID>? osmUIDs) =>
          (super.noSuchMethod(Invocation.method(#requestProductsAtShops, [osmUIDs]),
              returnValue:
                  Future<_i2.Result<List<_i27.BackendProductsAtShop>, _i19.BackendError>>.value(
                      _FakeResult_0<List<_i27.BackendProductsAtShop>,
                          _i19.BackendError>())) as _i9
              .Future<_i2.Result<List<_i27.BackendProductsAtShop>, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<List<_i29.BackendShop>, _i19.BackendError>>
      requestShopsByOsmUIDs(Iterable<_i28.OsmUID>? osmUIDs) => (super.noSuchMethod(
          Invocation.method(#requestShopsByOsmUIDs, [osmUIDs]),
          returnValue: Future<
                  _i2.Result<List<_i29.BackendShop>, _i19.BackendError>>.value(
              _FakeResult_0<List<_i29.BackendShop>, _i19.BackendError>())) as _i9
          .Future<_i2.Result<List<_i29.BackendShop>, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i30.ShopsInBoundsResponse, _i19.BackendError>>
      requestShopsWithin(_i31.CoordsBounds? bounds) => (super.noSuchMethod(
          Invocation.method(#requestShopsWithin, [bounds]),
          returnValue:
              Future<_i2.Result<_i30.ShopsInBoundsResponse, _i19.BackendError>>.value(
                  _FakeResult_0<_i30.ShopsInBoundsResponse,
                      _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i30.ShopsInBoundsResponse, _i19.BackendError>>);
  @override
  _i9.Future<
      _i2.Result<_i32.ProductPresenceVoteResult, _i19.BackendError>> productPresenceVote(
          String? barcode, _i28.OsmUID? osmUID, bool? positive) =>
      (super.noSuchMethod(
          Invocation.method(#productPresenceVote, [barcode, osmUID, positive]),
          returnValue:
              Future<_i2.Result<_i32.ProductPresenceVoteResult, _i19.BackendError>>.value(
                  _FakeResult_0<_i32.ProductPresenceVoteResult, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i32.ProductPresenceVoteResult, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> putProductToShop(
          String? barcode, _i12.Shop? shop, _i33.ProductAtShopSource? source) =>
      (super.noSuchMethod(
          Invocation.method(#putProductToShop, [barcode, shop, source]),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i29.BackendShop, _i19.BackendError>> createShop(
          {String? name, _i14.Coord? coord, String? type}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createShop, [], {#name: name, #coord: coord, #type: type}),
              returnValue:
                  Future<_i2.Result<_i29.BackendShop, _i19.BackendError>>.value(
                      _FakeResult_0<_i29.BackendShop, _i19.BackendError>()))
          as _i9.Future<_i2.Result<_i29.BackendShop, _i19.BackendError>>);
  @override
  _i9.Future<_i2.Result<_i34.NewsDataResponse, _i19.BackendError>> requestNews(
          _i31.CoordsBounds? bounds,
          {int? page}) =>
      (super.noSuchMethod(
              Invocation.method(#requestNews, [bounds], {#page: page}),
              returnValue: Future<
                      _i2.Result<_i34.NewsDataResponse, _i19.BackendError>>.value(
                  _FakeResult_0<_i34.NewsDataResponse, _i19.BackendError>()))
          as _i9.Future<_i2.Result<_i34.NewsDataResponse, _i19.BackendError>>);
  @override
  _i9.Future<Map<String, String>> authHeaders(
          {String? backendClientTokenOverride}) =>
      (super.noSuchMethod(
              Invocation.method(#authHeaders, [],
                  {#backendClientTokenOverride: backendClientTokenOverride}),
              returnValue:
                  Future<Map<String, String>>.value(<String, String>{}))
          as _i9.Future<Map<String, String>>);
  @override
  _i9.Future<_i3.BackendResponse> customGet(String? path,
          [Map<String, dynamic>? queryParams, Map<String, String>? headers]) =>
      (super.noSuchMethod(
              Invocation.method(#customGet, [path, queryParams, headers]),
              returnValue:
                  Future<_i3.BackendResponse>.value(_FakeBackendResponse_1()))
          as _i9.Future<_i3.BackendResponse>);
  @override
  _i9.Future<R> customRequest<R extends _i35.BaseRequest>(
          String? path, _i36.ArgResCallback<Uri, R>? createRequest,
          {Map<String, dynamic>? queryParams, Map<String, String>? headers}) =>
      (super.noSuchMethod(
          Invocation.method(#customRequest, [path, createRequest],
              {#queryParams: queryParams, #headers: headers}),
          returnValue: Future<R>.value(null)) as _i9.Future<R>);
}

/// A class which mocks [BackendObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendObserver extends _i1.Mock implements _i17.BackendObserver {
  MockBackendObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onBackendError(_i19.BackendError? error) =>
      super.noSuchMethod(Invocation.method(#onBackendError, [error]),
          returnValueForMissingStub: null);
}

/// A class which mocks [ContributedByUserProductsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockContributedByUserProductsStorage extends _i1.Mock
    implements _i37.ContributedByUserProductsStorage {
  MockContributedByUserProductsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get storedProductsMax =>
      (super.noSuchMethod(Invocation.getter(#storedProductsMax), returnValue: 0)
          as int);
  @override
  bool get beingTested =>
      (super.noSuchMethod(Invocation.getter(#beingTested), returnValue: false)
          as bool);
  @override
  String get storageFileName =>
      (super.noSuchMethod(Invocation.getter(#storageFileName), returnValue: '')
          as String);
  @override
  _i9.Future<void> get inited => (super.noSuchMethod(Invocation.getter(#inited),
      returnValue: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Stream<void> updates() =>
      (super.noSuchMethod(Invocation.method(#updates, []),
          returnValue: Stream<void>.empty()) as _i9.Stream<void>);
  @override
  List<_i38.Product> getProducts() =>
      (super.noSuchMethod(Invocation.method(#getProducts, []),
          returnValue: <_i38.Product>[]) as List<_i38.Product>);
  @override
  _i9.Future<void> addProduct(_i38.Product? product) =>
      (super.noSuchMethod(Invocation.method(#addProduct, [product]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> setProducts(Iterable<_i38.Product>? products) =>
      (super.noSuchMethod(Invocation.method(#setProducts, [products]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> purgeForTesting() =>
      (super.noSuchMethod(Invocation.method(#purgeForTesting, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
}

/// A class which mocks [DirectionsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectionsManager extends _i1.Mock implements _i39.DirectionsManager {
  MockDirectionsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<bool> areDirectionsAvailable() =>
      (super.noSuchMethod(Invocation.method(#areDirectionsAvailable, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  void direct(_i14.Coord? destination, String? destinationTitle) => super
      .noSuchMethod(Invocation.method(#direct, [destination, destinationTitle]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GeolocatorWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocatorWrapper extends _i1.Mock implements _i40.GeolocatorWrapper {
  MockGeolocatorWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i14.Coord?> getLastKnownPosition() =>
      (super.noSuchMethod(Invocation.method(#getLastKnownPosition, []),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
  @override
  _i9.Future<_i14.Coord?> getCurrentPosition() =>
      (super.noSuchMethod(Invocation.method(#getCurrentPosition, []),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
  @override
  _i9.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(Invocation.method(#isLocationServiceEnabled, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [GoogleAuthorizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthorizer extends _i1.Mock implements _i41.GoogleAuthorizer {
  MockGoogleAuthorizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i42.GoogleUser?> auth() =>
      (super.noSuchMethod(Invocation.method(#auth, []),
              returnValue: Future<_i42.GoogleUser?>.value())
          as _i9.Future<_i42.GoogleUser?>);
}

/// A class which mocks [GoogleMapController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleMapController extends _i1.Mock
    implements _i43.GoogleMapController {
  MockGoogleMapController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get mapId =>
      (super.noSuchMethod(Invocation.getter(#mapId), returnValue: 0) as int);
  @override
  _i9.Future<void> clearTileCache(_i4.TileOverlayId? tileOverlayId) =>
      (super.noSuchMethod(Invocation.method(#clearTileCache, [tileOverlayId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> animateCamera(_i4.CameraUpdate? cameraUpdate) =>
      (super.noSuchMethod(Invocation.method(#animateCamera, [cameraUpdate]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> moveCamera(_i4.CameraUpdate? cameraUpdate) =>
      (super.noSuchMethod(Invocation.method(#moveCamera, [cameraUpdate]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> setMapStyle(String? mapStyle) =>
      (super.noSuchMethod(Invocation.method(#setMapStyle, [mapStyle]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<_i4.LatLngBounds> getVisibleRegion() => (super.noSuchMethod(
          Invocation.method(#getVisibleRegion, []),
          returnValue: Future<_i4.LatLngBounds>.value(_FakeLatLngBounds_2()))
      as _i9.Future<_i4.LatLngBounds>);
  @override
  _i9.Future<_i4.ScreenCoordinate> getScreenCoordinate(_i4.LatLng? latLng) =>
      (super.noSuchMethod(Invocation.method(#getScreenCoordinate, [latLng]),
              returnValue:
                  Future<_i4.ScreenCoordinate>.value(_FakeScreenCoordinate_3()))
          as _i9.Future<_i4.ScreenCoordinate>);
  @override
  _i9.Future<_i4.LatLng> getLatLng(_i4.ScreenCoordinate? screenCoordinate) =>
      (super.noSuchMethod(Invocation.method(#getLatLng, [screenCoordinate]),
              returnValue: Future<_i4.LatLng>.value(_FakeLatLng_4()))
          as _i9.Future<_i4.LatLng>);
  @override
  _i9.Future<void> showMarkerInfoWindow(_i4.MarkerId? markerId) =>
      (super.noSuchMethod(Invocation.method(#showMarkerInfoWindow, [markerId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> hideMarkerInfoWindow(_i4.MarkerId? markerId) =>
      (super.noSuchMethod(Invocation.method(#hideMarkerInfoWindow, [markerId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<bool> isMarkerInfoWindowShown(_i4.MarkerId? markerId) => (super
      .noSuchMethod(Invocation.method(#isMarkerInfoWindowShown, [markerId]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<double> getZoomLevel() =>
      (super.noSuchMethod(Invocation.method(#getZoomLevel, []),
          returnValue: Future<double>.value(0.0)) as _i9.Future<double>);
  @override
  _i9.Future<_i20.Uint8List?> takeSnapshot() =>
      (super.noSuchMethod(Invocation.method(#takeSnapshot, []),
              returnValue: Future<_i20.Uint8List?>.value())
          as _i9.Future<_i20.Uint8List?>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [IpLocationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockIpLocationProvider extends _i1.Mock
    implements _i44.IpLocationProvider {
  MockIpLocationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i14.Coord?> positionByIP() =>
      (super.noSuchMethod(Invocation.method(#positionByIP, []),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
}

/// A class which mocks [LatestCameraPosStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLatestCameraPosStorage extends _i1.Mock
    implements _i45.LatestCameraPosStorage {
  MockLatestCameraPosStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> set(_i14.Coord? pos) =>
      (super.noSuchMethod(Invocation.method(#set, [pos]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<_i14.Coord?> get() =>
      (super.noSuchMethod(Invocation.method(#get, []),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
}

/// A class which mocks [UserLocationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocationManager extends _i1.Mock
    implements _i46.UserLocationManager {
  MockUserLocationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i14.Coord?> lastKnownPosition() =>
      (super.noSuchMethod(Invocation.method(#lastKnownPosition, []),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
  @override
  _i9.Future<_i14.Coord?> currentPosition({bool? explicitUserRequest}) =>
      (super.noSuchMethod(
          Invocation.method(#currentPosition, [],
              {#explicitUserRequest: explicitUserRequest}),
          returnValue: Future<_i14.Coord?>.value()) as _i9.Future<_i14.Coord?>);
  @override
  void callWhenLastPositionKnown(_i36.ArgCallback<_i14.Coord>? callback) =>
      super.noSuchMethod(
          Invocation.method(#callWhenLastPositionKnown, [callback]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MobileAppConfigManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMobileAppConfigManager extends _i1.Mock
    implements _i47.MobileAppConfigManager {
  MockMobileAppConfigManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> get initFuture =>
      (super.noSuchMethod(Invocation.getter(#initFuture),
          returnValue: Future<void>.value()) as _i9.Future<void>);
  @override
  void onUserParamsUpdate(_i18.UserParams? userParams) =>
      super.noSuchMethod(Invocation.method(#onUserParamsUpdate, [userParams]),
          returnValueForMissingStub: null);
  @override
  void addObserver(_i47.MobileAppConfigManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i47.MobileAppConfigManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<_i26.MobileAppConfig?> getConfig() =>
      (super.noSuchMethod(Invocation.method(#getConfig, []),
              returnValue: Future<_i26.MobileAppConfig?>.value())
          as _i9.Future<_i26.MobileAppConfig?>);
}

/// A class which mocks [OffApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffApi extends _i1.Mock implements _i48.OffApi {
  MockOffApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.SearchResult> getProductList(
          _i49.ProductListQueryConfiguration? configuration) =>
      (super.noSuchMethod(Invocation.method(#getProductList, [configuration]),
              returnValue:
                  Future<_i5.SearchResult>.value(_FakeSearchResult_5()))
          as _i9.Future<_i5.SearchResult>);
  @override
  _i9.Future<_i5.Status> saveProduct(_i5.User? user, _i5.Product? product) =>
      (super.noSuchMethod(Invocation.method(#saveProduct, [user, product]),
              returnValue: Future<_i5.Status>.value(_FakeStatus_6()))
          as _i9.Future<_i5.Status>);
  @override
  _i9.Future<_i5.Status> addProductImage(
          _i5.User? user, _i5.SendImage? image) =>
      (super.noSuchMethod(Invocation.method(#addProductImage, [user, image]),
              returnValue: Future<_i5.Status>.value(_FakeStatus_6()))
          as _i9.Future<_i5.Status>);
  @override
  _i9.Future<_i6.OcrIngredientsResult> extractIngredients(_i5.User? user,
          String? barcode, _i5.OpenFoodFactsLanguage? language) =>
      (super.noSuchMethod(
              Invocation.method(#extractIngredients, [user, barcode, language]),
              returnValue: Future<_i6.OcrIngredientsResult>.value(
                  _FakeOcrIngredientsResult_7()))
          as _i9.Future<_i6.OcrIngredientsResult>);
  @override
  _i9.Future<_i5.SearchResult> searchProducts(
          _i5.ProductSearchQueryConfiguration? configuration) =>
      (super.noSuchMethod(Invocation.method(#searchProducts, [configuration]),
              returnValue:
                  Future<_i5.SearchResult>.value(_FakeSearchResult_5()))
          as _i9.Future<_i5.SearchResult>);
  @override
  _i9.Future<_i2.Result<String, _i48.OffRestApiError>> getShopsJsonForCountry(
          String? countryIso) =>
      (super.noSuchMethod(
          Invocation.method(#getShopsJsonForCountry, [countryIso]),
          returnValue: Future<_i2.Result<String, _i48.OffRestApiError>>.value(
              _FakeResult_0<String, _i48.OffRestApiError>())) as _i9
          .Future<_i2.Result<String, _i48.OffRestApiError>>);
  @override
  _i9.Future<_i2.Result<List<String>, _i48.OffRestApiError>>
      getBarcodesVeganByIngredients(
              _i50.OffShop? shop, List<String>? productsCategories) =>
          (super.noSuchMethod(
              Invocation.method(
                  #getBarcodesVeganByIngredients, [shop, productsCategories]),
              returnValue:
                  Future<_i2.Result<List<String>, _i48.OffRestApiError>>.value(
                      _FakeResult_0<List<String>, _i48.OffRestApiError>())) as _i9
              .Future<_i2.Result<List<String>, _i48.OffRestApiError>>);
  @override
  _i9.Future<_i2.Result<List<String>, _i48.OffRestApiError>>
      getBarcodesVeganByLabel(_i50.OffShop? shop) => (super.noSuchMethod(
              Invocation.method(#getBarcodesVeganByLabel, [shop]),
              returnValue:
                  Future<_i2.Result<List<String>, _i48.OffRestApiError>>.value(
                      _FakeResult_0<List<String>, _i48.OffRestApiError>()))
          as _i9.Future<_i2.Result<List<String>, _i48.OffRestApiError>>);
}

/// A class which mocks [OffShopsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffShopsManager extends _i1.Mock implements _i51.OffShopsManager {
  MockOffShopsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i9.Future<_i2.Result<_i50.OffShop?, _i51.OffShopsManagerError>>
      findOffShopByName(String? name, String? countryCode) => (super.noSuchMethod(
          Invocation.method(#findOffShopByName, [name, countryCode]),
          returnValue: Future<
                  _i2.Result<_i50.OffShop?, _i51.OffShopsManagerError>>.value(
              _FakeResult_0<_i50.OffShop?, _i51.OffShopsManagerError>())) as _i9
          .Future<_i2.Result<_i50.OffShop?, _i51.OffShopsManagerError>>);
  @override
  _i9.Future<_i2.Result<List<_i50.OffShop>, _i51.OffShopsManagerError>>
      fetchOffShops(String? countryCode) => (super.noSuchMethod(
          Invocation.method(#fetchOffShops, [countryCode]),
          returnValue:
              Future<_i2.Result<List<_i50.OffShop>, _i51.OffShopsManagerError>>.value(
                  _FakeResult_0<List<_i50.OffShop>,
                      _i51.OffShopsManagerError>())) as _i9
          .Future<_i2.Result<List<_i50.OffShop>, _i51.OffShopsManagerError>>);
  @override
  _i9.Stream<_i2.Result<_i52.Pair<String, List<String>>, _i51.OffShopsManagerError>>
      fetchVeganBarcodes(Set<String>? shopsNames, String? countryCode) =>
          (super.noSuchMethod(
                  Invocation.method(#fetchVeganBarcodes, [shopsNames, countryCode]),
                  returnValue:
                      Stream<_i2.Result<_i52.Pair<String, List<String>>, _i51.OffShopsManagerError>>.empty())
              as _i9.Stream<
                  _i2.Result<_i52.Pair<String, List<String>>,
                      _i51.OffShopsManagerError>>);
}

/// A class which mocks [OsmNominatim].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmNominatim extends _i1.Mock implements _i53.OsmNominatim {
  MockOsmNominatim() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>> fetchAddress(
          double? lat, double? lon, {String? langCode}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAddress, [lat, lon], {#langCode: langCode}),
              returnValue: Future<
                      _i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<_i13.OsmAddress, _i11.OpenStreetMapError>()))
          as _i9.Future<_i2.Result<_i13.OsmAddress, _i11.OpenStreetMapError>>);
  @override
  _i9.Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>> search(
          String? country, String? city, String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [country, city, query]),
          returnValue:
              Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<_i54.OsmSearchResult,
                      _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>>);
}

/// A class which mocks [OsmOverpass].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmOverpass extends _i1.Mock implements _i55.OsmOverpass {
  MockOsmOverpass() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get urls => (super.noSuchMethod(Invocation.getter(#urls),
      returnValue: <String, String>{}) as Map<String, String>);
  @override
  int now() =>
      (super.noSuchMethod(Invocation.method(#now, []), returnValue: 0) as int);
  @override
  _i9.Future<_i2.Result<List<_i56.OsmShop>, _i11.OpenStreetMapError>> fetchShops(
          {_i31.CoordsBounds? bounds, Iterable<_i28.OsmUID>? osmUIDs}) =>
      (super.noSuchMethod(
          Invocation.method(
              #fetchShops, [], {#bounds: bounds, #osmUIDs: osmUIDs}),
          returnValue:
              Future<_i2.Result<List<_i56.OsmShop>, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<List<_i56.OsmShop>, _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<List<_i56.OsmShop>, _i11.OpenStreetMapError>>);
  @override
  _i9.Future<_i2.Result<List<_i57.OsmRoad>, _i11.OpenStreetMapError>>
      fetchRoads(_i31.CoordsBounds? bounds) => (super.noSuchMethod(
          Invocation.method(#fetchRoads, [bounds]),
          returnValue: Future<
                  _i2.Result<List<_i57.OsmRoad>, _i11.OpenStreetMapError>>.value(
              _FakeResult_0<List<_i57.OsmRoad>, _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<List<_i57.OsmRoad>, _i11.OpenStreetMapError>>);
}

/// A class which mocks [OsmSearcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockOsmSearcher extends _i1.Mock implements _i58.OsmSearcher {
  MockOsmSearcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>> search(
          String? country, String? city, String? query) =>
      (super.noSuchMethod(Invocation.method(#search, [country, city, query]),
          returnValue:
              Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>>.value(
                  _FakeResult_0<_i54.OsmSearchResult,
                      _i11.OpenStreetMapError>())) as _i9
          .Future<_i2.Result<_i54.OsmSearchResult, _i11.OpenStreetMapError>>);
}

/// A class which mocks [PermissionsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsManager extends _i1.Mock
    implements _i59.PermissionsManager {
  MockPermissionsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i59.PermissionState> status(_i59.PermissionKind? permission) =>
      (super.noSuchMethod(Invocation.method(#status, [permission]),
              returnValue: Future<_i59.PermissionState>.value(
                  _i59.PermissionState.granted))
          as _i9.Future<_i59.PermissionState>);
  @override
  _i9.Future<_i59.PermissionState> request(_i59.PermissionKind? permission) =>
      (super.noSuchMethod(Invocation.method(#request, [permission]),
              returnValue: Future<_i59.PermissionState>.value(
                  _i59.PermissionState.granted))
          as _i9.Future<_i59.PermissionState>);
  @override
  _i9.Future<bool> openAppSettings() =>
      (super.noSuchMethod(Invocation.method(#openAppSettings, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [PhotosTaker].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotosTaker extends _i1.Mock implements _i60.PhotosTaker {
  MockPhotosTaker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<Uri?> takeAndCropPhoto(_i61.BuildContext? context,
          _i62.Directory? outFolder, _i63.PhotoRequester? requester,
          {bool? cropCircle = false,
          int? downsizeTo,
          _i64.SizeInt? minSize,
          int? compressQualityJpg}) =>
      (super.noSuchMethod(
          Invocation.method(#takeAndCropPhoto, [
            context,
            outFolder,
            requester
          ], {
            #cropCircle: cropCircle,
            #downsizeTo: downsizeTo,
            #minSize: minSize,
            #compressQualityJpg: compressQualityJpg
          }),
          returnValue: Future<Uri?>.value()) as _i9.Future<Uri?>);
  @override
  _i9.Future<Uri?> selectAndCropPhoto(_i61.BuildContext? context,
          _i62.Directory? outFolder, _i63.PhotoRequester? requester,
          {bool? cropCircle = false,
          int? downsizeTo,
          _i64.SizeInt? minSize,
          int? compressQualityJpg}) =>
      (super.noSuchMethod(
          Invocation.method(#selectAndCropPhoto, [
            context,
            outFolder,
            requester
          ], {
            #cropCircle: cropCircle,
            #downsizeTo: downsizeTo,
            #minSize: minSize,
            #compressQualityJpg: compressQualityJpg
          }),
          returnValue: Future<Uri?>.value()) as _i9.Future<Uri?>);
  @override
  _i9.Future<Uri?> cropPhoto(String? photoPath, _i61.BuildContext? context,
          _i62.Directory? outFolder,
          {bool? cropCircle = false,
          int? downsizeTo,
          _i64.SizeInt? minSize,
          int? compressQualityJpg}) =>
      (super.noSuchMethod(
          Invocation.method(#cropPhoto, [
            photoPath,
            context,
            outFolder
          ], {
            #cropCircle: cropCircle,
            #downsizeTo: downsizeTo,
            #minSize: minSize,
            #compressQualityJpg: compressQualityJpg
          }),
          returnValue: Future<Uri?>.value()) as _i9.Future<Uri?>);
  @override
  _i9.Future<_i2.Result<Uri, _i65.PlatformException>?> retrieveLostPhoto(
          _i63.PhotoRequester? requester) =>
      (super.noSuchMethod(Invocation.method(#retrieveLostPhoto, [requester]),
              returnValue:
                  Future<_i2.Result<Uri, _i65.PlatformException>?>.value())
          as _i9.Future<_i2.Result<Uri, _i65.PlatformException>?>);
}

/// A class which mocks [ProductsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsManager extends _i1.Mock implements _i66.ProductsManager {
  MockProductsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i38.Product?, _i67.ProductsManagerError>> getProduct(
          String? barcodeRaw, List<_i25.LangCode>? langsPrioritized) =>
      (super.noSuchMethod(
          Invocation.method(#getProduct, [barcodeRaw, langsPrioritized]),
          returnValue: Future<
                  _i2.Result<_i38.Product?, _i67.ProductsManagerError>>.value(
              _FakeResult_0<_i38.Product?, _i67.ProductsManagerError>())) as _i9
          .Future<_i2.Result<_i38.Product?, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i38.Product?, _i67.ProductsManagerError>> inflate(
          _i68.BackendProduct? backendProduct,
          List<_i25.LangCode>? langsPrioritized) =>
      (super.noSuchMethod(
          Invocation.method(#inflate, [backendProduct, langsPrioritized]),
          returnValue: Future<
                  _i2.Result<_i38.Product?, _i67.ProductsManagerError>>.value(
              _FakeResult_0<_i38.Product?, _i67.ProductsManagerError>())) as _i9
          .Future<_i2.Result<_i38.Product?, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>> getProducts(
          List<String>? barcodesRaw, List<_i25.LangCode>? langsPrioritized) =>
      (super.noSuchMethod(
          Invocation.method(#getProducts, [barcodesRaw, langsPrioritized]),
          returnValue:
              Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>.value(
                  _FakeResult_0<List<_i38.Product>,
                      _i67.ProductsManagerError>())) as _i9
          .Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>> inflateProducts(
          List<_i68.BackendProduct>? backendProducts,
          List<_i25.LangCode>? langsPrioritized) =>
      (super.noSuchMethod(
          Invocation.method(
              #inflateProducts, [backendProducts, langsPrioritized]),
          returnValue:
              Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>.value(
                  _FakeResult_0<List<_i38.Product>, _i67.ProductsManagerError>())) as _i9
          .Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>
      inflateOffProducts(List<_i5.Product>? offProducts,
              List<_i25.LangCode>? langsPrioritized) =>
          (super.noSuchMethod(
              Invocation.method(
                  #inflateOffProducts, [offProducts, langsPrioritized]),
              returnValue:
                  Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>.value(
                      _FakeResult_0<List<_i38.Product>, _i67.ProductsManagerError>())) as _i9
              .Future<_i2.Result<List<_i38.Product>, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i38.Product, _i67.ProductsManagerError>>
      createUpdateProduct(_i38.Product? product) => (super.noSuchMethod(
          Invocation.method(#createUpdateProduct, [product]),
          returnValue: Future<
                  _i2.Result<_i38.Product, _i67.ProductsManagerError>>.value(
              _FakeResult_0<_i38.Product, _i67.ProductsManagerError>())) as _i9
          .Future<_i2.Result<_i38.Product, _i67.ProductsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i66.ProductWithOCRIngredients, _i67.ProductsManagerError>>
      updateProductAndExtractIngredients(
              _i38.Product? product, _i25.LangCode? ingredientsLangCode) =>
          (super.noSuchMethod(Invocation.method(#updateProductAndExtractIngredients, [product, ingredientsLangCode]),
                  returnValue:
                      Future<_i2.Result<_i66.ProductWithOCRIngredients, _i67.ProductsManagerError>>.value(
                          _FakeResult_0<_i66.ProductWithOCRIngredients, _i67.ProductsManagerError>()))
              as _i9.Future<
                  _i2.Result<_i66.ProductWithOCRIngredients, _i67.ProductsManagerError>>);
  @override
  void addObserver(_i66.ProductsManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i66.ProductsManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
}

/// A class which mocks [ProductsObtainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsObtainer extends _i1.Mock implements _i69.ProductsObtainer {
  MockProductsObtainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i38.Product?, _i69.ProductsObtainerError>> getProduct(
          String? barcode) =>
      (super.noSuchMethod(Invocation.method(#getProduct, [barcode]),
              returnValue: Future<
                      _i2.Result<_i38.Product?,
                          _i69.ProductsObtainerError>>.value(
                  _FakeResult_0<_i38.Product?, _i69.ProductsObtainerError>()))
          as _i9.Future<_i2.Result<_i38.Product?, _i69.ProductsObtainerError>>);
  @override
  _i9.Future<_i2.Result<_i38.Product?, _i69.ProductsObtainerError>> inflate(
          _i68.BackendProduct? backendProduct) =>
      (super.noSuchMethod(Invocation.method(#inflate, [backendProduct]),
          returnValue: Future<
                  _i2.Result<_i38.Product?, _i69.ProductsObtainerError>>.value(
              _FakeResult_0<_i38.Product?, _i69.ProductsObtainerError>())) as _i9
          .Future<_i2.Result<_i38.Product?, _i69.ProductsObtainerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>
      getProducts(List<String>? barcodes) => (super.noSuchMethod(
          Invocation.method(#getProducts, [barcodes]),
          returnValue:
              Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>.value(
                  _FakeResult_0<List<_i38.Product>,
                      _i69.ProductsObtainerError>())) as _i9
          .Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>> inflateProducts(
          List<_i68.BackendProduct>? backendProducts) =>
      (super.noSuchMethod(
          Invocation.method(#inflateProducts, [backendProducts]),
          returnValue:
              Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>.value(
                  _FakeResult_0<List<_i38.Product>,
                      _i69.ProductsObtainerError>())) as _i9
          .Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>);
  @override
  _i9.Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>
      inflateOffProducts(List<_i5.Product>? offProducts) => (super.noSuchMethod(
          Invocation.method(#inflateOffProducts, [offProducts]),
          returnValue: Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>.value(
              _FakeResult_0<List<_i38.Product>,
                  _i69.ProductsObtainerError>())) as _i9
          .Future<_i2.Result<List<_i38.Product>, _i69.ProductsObtainerError>>);
}

/// A class which mocks [RoadsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoadsManager extends _i1.Mock implements _i70.RoadsManager {
  MockRoadsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<List<_i57.OsmRoad>, _i70.RoadsManagerError>>
      fetchRoadsWithinAndNearby(_i31.CoordsBounds? bounds) => (super.noSuchMethod(
              Invocation.method(#fetchRoadsWithinAndNearby, [bounds]),
              returnValue: Future<
                      _i2.Result<List<_i57.OsmRoad>, _i70.RoadsManagerError>>.value(
                  _FakeResult_0<List<_i57.OsmRoad>, _i70.RoadsManagerError>()))
          as _i9.Future<_i2.Result<List<_i57.OsmRoad>, _i70.RoadsManagerError>>);
}

/// A class which mocks [RouteObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteObserver<R extends _i61.Route<dynamic>> extends _i1.Mock
    implements _i61.RouteObserver<R> {
  MockRouteObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool debugObservingRoute(R? route) =>
      (super.noSuchMethod(Invocation.method(#debugObservingRoute, [route]),
          returnValue: false) as bool);
  @override
  void subscribe(_i61.RouteAware? routeAware, R? route) =>
      super.noSuchMethod(Invocation.method(#subscribe, [routeAware, route]),
          returnValueForMissingStub: null);
  @override
  void unsubscribe(_i61.RouteAware? routeAware) =>
      super.noSuchMethod(Invocation.method(#unsubscribe, [routeAware]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPush(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i61.Route<dynamic>? newRoute, _i61.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [ShopsCreationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopsCreationManager extends _i1.Mock
    implements _i71.ShopsCreationManager {
  MockShopsCreationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i12.Shop?, _i72.GeneralError>> startShopCreation(
          _i14.Coord? coord, _i61.BuildContext? context) =>
      (super.noSuchMethod(
          Invocation.method(#startShopCreation, [coord, context]),
          returnValue: Future<_i2.Result<_i12.Shop?, _i72.GeneralError>>.value(
              _FakeResult_0<_i12.Shop?, _i72.GeneralError>())) as _i9
          .Future<_i2.Result<_i12.Shop?, _i72.GeneralError>>);
}

/// A class which mocks [ShopsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopsManager extends _i1.Mock implements _i73.ShopsManager {
  MockShopsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get loadedAreasCount =>
      (super.noSuchMethod(Invocation.getter(#loadedAreasCount), returnValue: 0)
          as int);
  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void addListener(_i74.ShopsManagerListener? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i74.ShopsManagerListener? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<Map<_i28.OsmUID, List<String>>> getBarcodesWithin(
          _i31.CoordsBounds? bounds) =>
      (super.noSuchMethod(Invocation.method(#getBarcodesWithin, [bounds]),
              returnValue: Future<Map<_i28.OsmUID, List<String>>>.value(
                  <_i28.OsmUID, List<String>>{}))
          as _i9.Future<Map<_i28.OsmUID, List<String>>>);
  @override
  _i9.Future<Map<_i28.OsmUID, List<String>>> getBarcodesCacheFor(
          Iterable<_i28.OsmUID>? uids) =>
      (super.noSuchMethod(Invocation.method(#getBarcodesCacheFor, [uids]),
              returnValue: Future<Map<_i28.OsmUID, List<String>>>.value(
                  <_i28.OsmUID, List<String>>{}))
          as _i9.Future<Map<_i28.OsmUID, List<String>>>);
  @override
  _i9.Future<Map<_i28.OsmUID, _i12.Shop>> getCachedShopsFor(
          Iterable<_i28.OsmUID>? uids) =>
      (super.noSuchMethod(Invocation.method(#getCachedShopsFor, [uids]),
              returnValue: Future<Map<_i28.OsmUID, _i12.Shop>>.value(
                  <_i28.OsmUID, _i12.Shop>{}))
          as _i9.Future<Map<_i28.OsmUID, _i12.Shop>>);
  @override
  _i9.Future<bool> osmShopsCacheExistFor(_i31.CoordsBounds? bounds) =>
      (super.noSuchMethod(Invocation.method(#osmShopsCacheExistFor, [bounds]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>
      fetchShops(_i31.CoordsBounds? bounds) =>
          (super.noSuchMethod(Invocation.method(#fetchShops, [bounds]),
              returnValue:
                  Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>.value(
                      _FakeResult_0<Map<_i28.OsmUID, _i12.Shop>,
                          _i74.ShopsManagerError>())) as _i9
              .Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>);
  @override
  _i9.Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>
      inflateOsmShops(Iterable<_i56.OsmShop>? shops) =>
          (super.noSuchMethod(Invocation.method(#inflateOsmShops, [shops]),
              returnValue:
                  Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>.value(
                      _FakeResult_0<Map<_i28.OsmUID, _i12.Shop>,
                          _i74.ShopsManagerError>())) as _i9
              .Future<_i2.Result<Map<_i28.OsmUID, _i12.Shop>, _i74.ShopsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i75.ShopProductRange, _i74.ShopsManagerError>>
      fetchShopProductRange(_i12.Shop? shop, {bool? noCache = false}) => (super
          .noSuchMethod(
              Invocation.method(
                  #fetchShopProductRange, [shop], {#noCache: noCache}),
              returnValue:
                  Future<_i2.Result<_i75.ShopProductRange, _i74.ShopsManagerError>>.value(
                      _FakeResult_0<_i75.ShopProductRange, _i74.ShopsManagerError>())) as _i9
          .Future<_i2.Result<_i75.ShopProductRange, _i74.ShopsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i2.None, _i74.ShopsManagerError>> putProductToShops(
          _i38.Product? product,
          List<_i12.Shop>? shops,
          _i33.ProductAtShopSource? source) =>
      (super.noSuchMethod(
              Invocation.method(#putProductToShops, [product, shops, source]),
              returnValue:
                  Future<_i2.Result<_i2.None, _i74.ShopsManagerError>>.value(
                      _FakeResult_0<_i2.None, _i74.ShopsManagerError>()))
          as _i9.Future<_i2.Result<_i2.None, _i74.ShopsManagerError>>);
  @override
  _i9.Future<_i2.Result<_i12.Shop, _i74.ShopsManagerError>> createShop(
          {String? name, _i14.Coord? coord, _i76.ShopType? type}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createShop, [], {#name: name, #coord: coord, #type: type}),
              returnValue:
                  Future<_i2.Result<_i12.Shop, _i74.ShopsManagerError>>.value(
                      _FakeResult_0<_i12.Shop, _i74.ShopsManagerError>()))
          as _i9.Future<_i2.Result<_i12.Shop, _i74.ShopsManagerError>>);
  @override
  _i9.Future<
      _i2.Result<_i32.ProductPresenceVoteResult, _i74.ShopsManagerError>> productPresenceVote(
          _i38.Product? product, _i12.Shop? shop, bool? positive) =>
      (super.noSuchMethod(
          Invocation.method(#productPresenceVote, [product, shop, positive]),
          returnValue:
              Future<_i2.Result<_i32.ProductPresenceVoteResult, _i74.ShopsManagerError>>.value(
                  _FakeResult_0<_i32.ProductPresenceVoteResult, _i74.ShopsManagerError>())) as _i9
          .Future<_i2.Result<_i32.ProductPresenceVoteResult, _i74.ShopsManagerError>>);
  @override
  _i9.Future<void> clearCache() =>
      (super.noSuchMethod(Invocation.method(#clearCache, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
}

/// A class which mocks [ShopsManagerListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopsManagerListener extends _i1.Mock
    implements _i74.ShopsManagerListener {
  MockShopsManagerListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onLocalShopsChange() =>
      super.noSuchMethod(Invocation.method(#onLocalShopsChange, []),
          returnValueForMissingStub: null);
  @override
  void onShopCreated(_i12.Shop? shop) =>
      super.noSuchMethod(Invocation.method(#onShopCreated, [shop]),
          returnValueForMissingStub: null);
  @override
  void onProductPutToShops(_i38.Product? product, List<_i12.Shop>? shops) =>
      super.noSuchMethod(
          Invocation.method(#onProductPutToShops, [product, shops]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SuggestedProductsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestedProductsManager extends _i1.Mock
    implements _i77.SuggestedProductsManager {
  MockSuggestedProductsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i2.Result<_i78.SuggestionsForShop, _i77.SuggestedProductsManagerError>>
      getSuggestedBarcodes(Iterable<_i12.Shop>? shops, _i14.Coord? center,
              String? countryCode, {Set<_i79.SuggestionType>? types}) =>
          (super.noSuchMethod(
                  Invocation.method(#getSuggestedBarcodes,
                      [shops, center, countryCode], {#types: types}),
                  returnValue: Stream<_i2.Result<_i78.SuggestionsForShop, _i77.SuggestedProductsManagerError>>.empty())
              as _i9.Stream<_i2.Result<_i78.SuggestionsForShop, _i77.SuggestedProductsManagerError>>);
}

/// A class which mocks [SysLangCodeHolder].
///
/// See the documentation for Mockito's code generation for more information.
class MockSysLangCodeHolder extends _i1.Mock implements _i80.SysLangCodeHolder {
  MockSysLangCodeHolder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get langCode =>
      (super.noSuchMethod(Invocation.getter(#langCode), returnValue: '')
          as String);
  @override
  set langCode(String? value) =>
      super.noSuchMethod(Invocation.setter(#langCode, value),
          returnValueForMissingStub: null);
  @override
  _i9.Future<String> get langCodeInited =>
      (super.noSuchMethod(Invocation.getter(#langCodeInited),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  void callWhenInited(_i36.ArgCallback<String>? callback) =>
      super.noSuchMethod(Invocation.method(#callWhenInited, [callback]),
          returnValueForMissingStub: null);
}

/// A class which mocks [UserLangsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLangsManager extends _i1.Mock implements _i81.UserLangsManager {
  MockUserLangsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> get initFuture =>
      (super.noSuchMethod(Invocation.getter(#initFuture),
          returnValue: Future<void>.value()) as _i9.Future<void>);
  @override
  void addObserver(_i81.UserLangsManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i81.UserLangsManagerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<_i7.UserLangs> getUserLangs() =>
      (super.noSuchMethod(Invocation.method(#getUserLangs, []),
              returnValue: Future<_i7.UserLangs>.value(_FakeUserLangs_8()))
          as _i9.Future<_i7.UserLangs>);
  @override
  _i9.Future<_i2.Result<_i18.UserParams, _i82.UserLangsManagerError>>
      setManualUserLangs(List<_i25.LangCode>? userLangs) => (super.noSuchMethod(
          Invocation.method(#setManualUserLangs, [userLangs]),
          returnValue: Future<
                  _i2.Result<_i18.UserParams, _i82.UserLangsManagerError>>.value(
              _FakeResult_0<_i18.UserParams, _i82.UserLangsManagerError>())) as _i9
          .Future<_i2.Result<_i18.UserParams, _i82.UserLangsManagerError>>);
}

/// A class which mocks [UserLangsManagerObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLangsManagerObserver extends _i1.Mock
    implements _i81.UserLangsManagerObserver {
  MockUserLangsManagerObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onUserLangsChange(_i7.UserLangs? userLangs) =>
      super.noSuchMethod(Invocation.method(#onUserLangsChange, [userLangs]),
          returnValueForMissingStub: null);
}

/// A class which mocks [UserParamsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserParamsController extends _i1.Mock
    implements _i83.UserParamsController {
  MockUserParamsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addObserver(_i83.UserParamsControllerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i83.UserParamsControllerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<_i18.UserParams?> getUserParams() =>
      (super.noSuchMethod(Invocation.method(#getUserParams, []),
              returnValue: Future<_i18.UserParams?>.value())
          as _i9.Future<_i18.UserParams?>);
  @override
  _i9.Future<void> setUserParams(_i18.UserParams? userParams) =>
      (super.noSuchMethod(Invocation.method(#setUserParams, [userParams]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
}

/// A class which mocks [UserReportsMaker].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserReportsMaker extends _i1.Mock implements _i84.UserReportsMaker {
  MockUserReportsMaker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<_i2.None, _i19.BackendError>> reportProduct(
          String? barcode, String? reportText) =>
      (super.noSuchMethod(
          Invocation.method(#reportProduct, [barcode, reportText]),
          returnValue: Future<_i2.Result<_i2.None, _i19.BackendError>>.value(
              _FakeResult_0<_i2.None, _i19.BackendError>())) as _i9
          .Future<_i2.Result<_i2.None, _i19.BackendError>>);
  @override
  void addObserver(_i84.UserReportsMakerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i84.UserReportsMakerObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
}

/// A class which mocks [ViewedProductsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewedProductsStorage extends _i1.Mock
    implements _i85.ViewedProductsStorage {
  MockViewedProductsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get storedProductsMax =>
      (super.noSuchMethod(Invocation.getter(#storedProductsMax), returnValue: 0)
          as int);
  @override
  bool get beingTested =>
      (super.noSuchMethod(Invocation.getter(#beingTested), returnValue: false)
          as bool);
  @override
  String get storageFileName =>
      (super.noSuchMethod(Invocation.getter(#storageFileName), returnValue: '')
          as String);
  @override
  _i9.Future<void> get inited => (super.noSuchMethod(Invocation.getter(#inited),
      returnValue: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Stream<void> updates() =>
      (super.noSuchMethod(Invocation.method(#updates, []),
          returnValue: Stream<void>.empty()) as _i9.Stream<void>);
  @override
  List<_i38.Product> getProducts() =>
      (super.noSuchMethod(Invocation.method(#getProducts, []),
          returnValue: <_i38.Product>[]) as List<_i38.Product>);
  @override
  _i9.Future<void> addProduct(_i38.Product? product) =>
      (super.noSuchMethod(Invocation.method(#addProduct, [product]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> setProducts(Iterable<_i38.Product>? products) =>
      (super.noSuchMethod(Invocation.method(#setProducts, [products]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> purgeForTesting() =>
      (super.noSuchMethod(Invocation.method(#purgeForTesting, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i61.NavigatorObserver {
  @override
  void didPush(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i61.Route<dynamic>? newRoute, _i61.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i61.Route<dynamic>? route, _i61.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}
