// Mocks generated by Mockito 5.0.2 from annotations
// in untitled_vegan_app/test/ui/first_screen/external_auth_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:untitled_vegan_app/identity/google_authorizer.dart' as _i3;
import 'package:untitled_vegan_app/identity/google_user.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeGoogleUser extends _i1.Fake implements _i2.GoogleUser {}

/// A class which mocks [GoogleAuthorizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthorizer extends _i1.Mock implements _i3.GoogleAuthorizer {
  MockGoogleAuthorizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GoogleUser?> auth() =>
      (super.noSuchMethod(Invocation.method(#auth, []),
              returnValue: Future.value(_FakeGoogleUser()))
          as _i4.Future<_i2.GoogleUser?>);
}
