name: plante
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 24.01.240+66

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  built_collection: ^5.0.0
  built_value: ^8.0.4
  cached_network_image: ^3.2.0
  crop_your_image: ^0.7.4
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  diffutil_dart: ^3.0.0
  expandable: ^5.0.1
  fimber: ^0.6.1
  fimber_io: ^0.6.2
  flutter_archive: ^6.0.0
  flutter_image_compress: ^2.1.0
  flutter_linkify: ^5.0.2
  flutter_riverpod: ^1.0.0
  flutter_svg: ^2.0.9
  fuzzywuzzy: ^0.2.0
  geolocator: ^9.0.2
  get_it: ^7.1.3
  google_maps_cluster_manager: ^1.0.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.1
  http: ^0.13.3
  image_picker: ^0.8.0+1
  intl: ^0.18.0
  map_launcher: ^3.1.0
  openfoodfacts:
    path: submodules/openfoodfacts-dart
  package_info_plus: ^4.0.2
  palette_generator: ^0.3.0
  path_provider: ^2.0.1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  mobile_scanner: ^3.5.6
  share_plus: ^7.2.1
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^5.0.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  stack_trace: ^1.10.0
  url_launcher: ^6.0.10
  visibility_detector: ^0.3.3
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  test: ^1.16.8
  trotter: ^2.0.0-dev.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"
  image_path_ios: "icon/icon_ios.png"
  adaptive_icon_background: "icon/icon_android_background.png"
  adaptive_icon_foreground: "icon/icon_android_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

  assets:
    - .env
    - assets/add_photo.svg
    - assets/add_photo_background.svg
    - assets/back_arrow.svg
    - assets/barcode_scan_mode.svg
    - assets/barcode_type_mode.svg
    - assets/bottom_bar_barcode.svg
    - assets/bottom_bar_history.svg
    - assets/bottom_bar_map.svg
    - assets/bottom_bar_plus.svg
    - assets/bottom_bar_profile.svg
    - assets/bottom_bar_news_feed.svg
    - assets/cancel_circle_light.svg
    - assets/cancel_circle.svg
    - assets/cancel.svg
    - assets/contact_discord.png
    - assets/contact_email.png
    - assets/contact_facebook.png
    - assets/contact_instagram.png
    - assets/contact_telegram.png
    - assets/contact_vk.png
    - assets/copy.svg
    - assets/directions.svg
    - assets/empty.svg
    - assets/expand_down.svg
    - assets/expand_up.svg
    - assets/flash_disabled.svg
    - assets/flash_enabled.svg
    - assets/google_icon.svg
    - assets/info_icon.svg
    - assets/list_drag_n_drop.svg
    - assets/like.svg
    - assets/like_filled.svg
    - assets/location.svg
    - assets/map_check_mark.svg
    - assets/map_marker_accented.svg
    - assets/map_marker_empty.svg
    - assets/map_marker_filled.svg
    - assets/map_marker_group_accented.svg
    - assets/map_marker_group_empty.svg
    - assets/map_marker_group_filled.svg
    - assets/map_marker_group_selected.svg
    - assets/map_marker_group_suggestions.svg
    - assets/map_marker_selected.svg
    - assets/map_marker_suggestions.svg
    - assets/menu_ellipsis.svg
    - assets/my_location.svg
    - assets/plus_shop.svg
    - assets/plus_small.svg
    - assets/scroll_to_top.svg
    - assets/search.svg
    - assets/settings.svg
    - assets/show_on_map_small.svg
    - assets/veg_status_negative.svg
    - assets/veg_status_source_auto.svg
    - assets/veg_status_source_community.svg
    - assets/veg_status_source_moderator.svg
    - assets/veg_status_source_unknown.svg
    - assets/veg_status_unknown.png
    - assets/veg_status_vegan.svg
    - assets/veg_status_warning_icon.svg
    - assets/news_piece_shop_location.svg
