// Mocks generated by Mockito 5.0.3 from annotations
// in plante/test/outside/products/products_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:openfoodfacts/model/OcrIngredientsResult.dart' as _i4;
import 'package:openfoodfacts/model/Product.dart' as _i10;
import 'package:openfoodfacts/model/ProductResult.dart' as _i2;
import 'package:openfoodfacts/model/SendImage.dart' as _i11;
import 'package:openfoodfacts/model/Status.dart' as _i3;
import 'package:openfoodfacts/model/User.dart' as _i9;
import 'package:openfoodfacts/utils/LanguageHelper.dart' as _i12;
import 'package:openfoodfacts/utils/ProductQueryConfigurations.dart' as _i8;
import 'package:plante/base/result.dart' as _i5;
import 'package:plante/model/user_params.dart' as _i14;
import 'package:plante/model/veg_status.dart' as _i17;
import 'package:plante/outside/backend/backend.dart' as _i13;
import 'package:plante/outside/backend/backend_error.dart' as _i15;
import 'package:plante/outside/backend/backend_product.dart' as _i16;
import 'package:plante/outside/backend/backend_products_at_shop.dart' as _i18;
import 'package:plante/outside/backend/backend_shop.dart' as _i19;
import 'package:plante/outside/off/off_api.dart' as _i6;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeProductResult extends _i1.Fake implements _i2.ProductResult {}

class _FakeStatus extends _i1.Fake implements _i3.Status {}

class _FakeOcrIngredientsResult extends _i1.Fake
    implements _i4.OcrIngredientsResult {}

class _FakeResult<OK, ERR> extends _i1.Fake implements _i5.Result<OK, ERR> {}

/// A class which mocks [OffApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffApi extends _i1.Mock implements _i6.OffApi {
  MockOffApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ProductResult> getProduct(
          _i8.ProductQueryConfiguration? configuration) =>
      (super.noSuchMethod(Invocation.method(#getProduct, [configuration]),
              returnValue: Future.value(_FakeProductResult()))
          as _i7.Future<_i2.ProductResult>);
  @override
  _i7.Future<_i3.Status> saveProduct(_i9.User? user, _i10.Product? product) =>
      (super.noSuchMethod(Invocation.method(#saveProduct, [user, product]),
          returnValue: Future.value(_FakeStatus())) as _i7.Future<_i3.Status>);
  @override
  _i7.Future<_i3.Status> addProductImage(
          _i9.User? user, _i11.SendImage? image) =>
      (super.noSuchMethod(Invocation.method(#addProductImage, [user, image]),
          returnValue: Future.value(_FakeStatus())) as _i7.Future<_i3.Status>);
  @override
  _i7.Future<_i4.OcrIngredientsResult> extractIngredients(_i9.User? user,
          String? barcode, _i12.OpenFoodFactsLanguage? language) =>
      (super.noSuchMethod(
              Invocation.method(#extractIngredients, [user, barcode, language]),
              returnValue: Future.value(_FakeOcrIngredientsResult()))
          as _i7.Future<_i4.OcrIngredientsResult>);
}

/// A class which mocks [Backend].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackend extends _i1.Mock implements _i13.Backend {
  MockBackend() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addObserver(_i13.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i13.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
          returnValue: Future.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i5.Result<_i14.UserParams, _i15.BackendError>> loginOrRegister(
          String? googleIdToken) =>
      (super.noSuchMethod(Invocation.method(#loginOrRegister, [googleIdToken]),
              returnValue: Future.value(
                  _FakeResult<_i14.UserParams, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i14.UserParams, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<bool, _i15.BackendError>> updateUserParams(
          _i14.UserParams? userParams,
          {String? backendClientTokenOverride}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUserParams, [userParams],
                  {#backendClientTokenOverride: backendClientTokenOverride}),
              returnValue: Future.value(_FakeResult<bool, _i15.BackendError>()))
          as _i7.Future<_i5.Result<bool, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i16.BackendProduct?, _i15.BackendError>>
      requestProduct(String? barcode) => (super.noSuchMethod(
              Invocation.method(#requestProduct, [barcode]),
              returnValue: Future.value(
                  _FakeResult<_i16.BackendProduct?, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i16.BackendProduct?, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i5.None, _i15.BackendError>> createUpdateProduct(
          String? barcode,
          {_i17.VegStatus? vegetarianStatus,
          _i17.VegStatus? veganStatus}) =>
      (super.noSuchMethod(
              Invocation.method(#createUpdateProduct, [
                barcode
              ], {
                #vegetarianStatus: vegetarianStatus,
                #veganStatus: veganStatus
              }),
              returnValue:
                  Future.value(_FakeResult<_i5.None, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i5.None, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i5.None, _i15.BackendError>> sendReport(
          String? barcode, String? reportText) =>
      (super.noSuchMethod(Invocation.method(#sendReport, [barcode, reportText]),
              returnValue:
                  Future.value(_FakeResult<_i5.None, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i5.None, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i5.None, _i15.BackendError>> sendProductScan(
          String? barcode) =>
      (super.noSuchMethod(Invocation.method(#sendProductScan, [barcode]),
              returnValue:
                  Future.value(_FakeResult<_i5.None, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i5.None, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i14.UserParams, _i15.BackendError>> userData() =>
      (super.noSuchMethod(Invocation.method(#userData, []),
              returnValue: Future.value(
                  _FakeResult<_i14.UserParams, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i14.UserParams, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<List<_i18.BackendProductsAtShop>, _i15.BackendError>>
      requestProductsAtShops(Iterable<String>? osmIds) => (super.noSuchMethod(
          Invocation.method(#requestProductsAtShops, [osmIds]),
          returnValue: Future.value(_FakeResult<
              List<_i18.BackendProductsAtShop>, _i15.BackendError>())) as _i7
          .Future<_i5.Result<List<_i18.BackendProductsAtShop>, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<List<_i19.BackendShop>, _i15.BackendError>>
      requestShops(Iterable<String>? osmIds) => (super.noSuchMethod(
              Invocation.method(#requestShops, [osmIds]),
              returnValue: Future.value(
                  _FakeResult<List<_i19.BackendShop>, _i15.BackendError>()))
          as _i7.Future<_i5.Result<List<_i19.BackendShop>, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i5.None, _i15.BackendError>> productPresenceVote(
          String? barcode, String? osmId, bool? positive) =>
      (super.noSuchMethod(
          Invocation.method(#productPresenceVote, [barcode, osmId, positive]),
          returnValue:
              Future.value(_FakeResult<_i5.None, _i15.BackendError>())) as _i7
          .Future<_i5.Result<_i5.None, _i15.BackendError>>);
  @override
  _i7.Future<_i5.Result<_i5.None, _i15.BackendError>> putProductToShop(
          String? barcode, String? osmId) =>
      (super.noSuchMethod(
              Invocation.method(#putProductToShop, [barcode, osmId]),
              returnValue:
                  Future.value(_FakeResult<_i5.None, _i15.BackendError>()))
          as _i7.Future<_i5.Result<_i5.None, _i15.BackendError>>);
}
