// Mocks generated by Mockito 5.0.10 from annotations
// in plante/test/outside/backend/backend_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:plante/outside/backend/backend.dart' as _i2;
import 'package:plante/outside/backend/backend_error.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [BackendObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendObserver extends _i1.Mock implements _i2.BackendObserver {
  MockBackendObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onBackendError(_i3.BackendError? error) =>
      super.noSuchMethod(Invocation.method(#onBackendError, [error]),
          returnValueForMissingStub: null);
}
