// Mocks generated by Mockito 5.0.10 from annotations
// in plante/test/ui/map/map_page_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:math' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:plante/base/base.dart' as _i6;
import 'package:plante/base/result.dart' as _i2;
import 'package:plante/location/location_controller.dart' as _i3;
import 'package:plante/model/product.dart' as _i11;
import 'package:plante/model/shop.dart' as _i9;
import 'package:plante/model/shop_product_range.dart' as _i10;
import 'package:plante/model/shop_type.dart' as _i12;
import 'package:plante/outside/map/shops_manager.dart' as _i7;
import 'package:plante/outside/map/shops_manager_types.dart' as _i8;
import 'package:plante/ui/map/latest_camera_pos_storage.dart' as _i13;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<OK, ERR> extends _i1.Fake implements _i2.Result<OK, ERR> {}

/// A class which mocks [LocationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationController extends _i1.Mock
    implements _i3.LocationController {
  MockLocationController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Point<double>?> lastKnownPosition() =>
      (super.noSuchMethod(Invocation.method(#lastKnownPosition, []),
              returnValue: Future<_i5.Point<double>?>.value())
          as _i4.Future<_i5.Point<double>?>);
  @override
  _i4.Future<_i5.Point<double>?> currentPosition() =>
      (super.noSuchMethod(Invocation.method(#currentPosition, []),
              returnValue: Future<_i5.Point<double>?>.value())
          as _i4.Future<_i5.Point<double>?>);
  @override
  void callWhenLastPositionKnown(
          _i6.ArgCallback<_i5.Point<double>>? callback) =>
      super.noSuchMethod(
          Invocation.method(#callWhenLastPositionKnown, [callback]),
          returnValueForMissingStub: null);
}

/// A class which mocks [ShopsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopsManager extends _i1.Mock implements _i7.ShopsManager {
  MockShopsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get loadedAreasCount =>
      (super.noSuchMethod(Invocation.getter(#loadedAreasCount), returnValue: 0)
          as int);
  @override
  void addListener(_i8.ShopsManagerListener? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i8.ShopsManagerListener? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.Result<Map<String, _i9.Shop>, _i8.ShopsManagerError>> fetchShops(
          _i5.Point<double>? northeast, _i5.Point<double>? southwest) =>
      (super.noSuchMethod(
          Invocation.method(#fetchShops, [northeast, southwest]),
          returnValue: Future<
                  _i2.Result<Map<String, _i9.Shop>, _i8.ShopsManagerError>>.value(
              _FakeResult<Map<String, _i9.Shop>, _i8.ShopsManagerError>())) as _i4
          .Future<_i2.Result<Map<String, _i9.Shop>, _i8.ShopsManagerError>>);
  @override
  _i4.Future<_i2.Result<_i10.ShopProductRange, _i8.ShopsManagerError>>
      fetchShopProductRange(_i9.Shop? shop, {bool? noCache = false}) => (super
          .noSuchMethod(
              Invocation.method(
                  #fetchShopProductRange, [shop], {#noCache: noCache}),
              returnValue:
                  Future<_i2.Result<_i10.ShopProductRange, _i8.ShopsManagerError>>.value(
                      _FakeResult<_i10.ShopProductRange, _i8.ShopsManagerError>())) as _i4
          .Future<_i2.Result<_i10.ShopProductRange, _i8.ShopsManagerError>>);
  @override
  _i4.Future<_i2.Result<_i2.None, _i8.ShopsManagerError>> putProductToShops(
          _i11.Product? product, List<_i9.Shop>? shops) =>
      (super.noSuchMethod(
              Invocation.method(#putProductToShops, [product, shops]),
              returnValue:
                  Future<_i2.Result<_i2.None, _i8.ShopsManagerError>>.value(
                      _FakeResult<_i2.None, _i8.ShopsManagerError>()))
          as _i4.Future<_i2.Result<_i2.None, _i8.ShopsManagerError>>);
  @override
  _i4.Future<_i2.Result<_i9.Shop, _i8.ShopsManagerError>> createShop(
          {String? name, _i5.Point<double>? coords, _i12.ShopType? type}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createShop, [], {#name: name, #coords: coords, #type: type}),
              returnValue:
                  Future<_i2.Result<_i9.Shop, _i8.ShopsManagerError>>.value(
                      _FakeResult<_i9.Shop, _i8.ShopsManagerError>()))
          as _i4.Future<_i2.Result<_i9.Shop, _i8.ShopsManagerError>>);
}

/// A class which mocks [LatestCameraPosStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLatestCameraPosStorage extends _i1.Mock
    implements _i13.LatestCameraPosStorage {
  MockLatestCameraPosStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> set(_i5.Point<double>? pos) =>
      (super.noSuchMethod(Invocation.method(#set, [pos]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<_i5.Point<double>?> get() =>
      (super.noSuchMethod(Invocation.method(#get, []),
              returnValue: Future<_i5.Point<double>?>.value())
          as _i4.Future<_i5.Point<double>?>);
}
