// Mocks generated by Mockito 5.0.10 from annotations
// in plante/test/ui/scan/viewed_products_history_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:math' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:plante/base/result.dart' as _i2;
import 'package:plante/model/product.dart' as _i6;
import 'package:plante/model/user_params.dart' as _i10;
import 'package:plante/model/veg_status.dart' as _i12;
import 'package:plante/outside/backend/backend.dart' as _i9;
import 'package:plante/outside/backend/backend_error.dart' as _i11;
import 'package:plante/outside/backend/backend_product.dart' as _i8;
import 'package:plante/outside/backend/backend_products_at_shop.dart' as _i13;
import 'package:plante/outside/backend/backend_response.dart' as _i3;
import 'package:plante/outside/backend/backend_shop.dart' as _i14;
import 'package:plante/outside/products/products_manager.dart' as _i4;
import 'package:plante/outside/products/products_manager_error.dart' as _i7;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<OK, ERR> extends _i1.Fake implements _i2.Result<OK, ERR> {}

class _FakeBackendResponse extends _i1.Fake implements _i3.BackendResponse {}

/// A class which mocks [ProductsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsManager extends _i1.Mock implements _i4.ProductsManager {
  MockProductsManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>> getProduct(
          String? barcodeRaw,
          [String? langCode]) =>
      (super.noSuchMethod(
          Invocation.method(#getProduct, [barcodeRaw, langCode]),
          returnValue:
              Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>>.value(
                  _FakeResult<_i6.Product?, _i7.ProductsManagerError>())) as _i5
          .Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>>);
  @override
  _i5.Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>> inflate(
          _i8.BackendProduct? backendProduct,
          [String? langCode]) =>
      (super.noSuchMethod(
          Invocation.method(#inflate, [backendProduct, langCode]),
          returnValue:
              Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>>.value(
                  _FakeResult<_i6.Product?, _i7.ProductsManagerError>())) as _i5
          .Future<_i2.Result<_i6.Product?, _i7.ProductsManagerError>>);
  @override
  _i5.Future<
      _i2.Result<_i6.Product, _i7.ProductsManagerError>> createUpdateProduct(
          _i6.Product? product,
          [String? langCode]) =>
      (super.noSuchMethod(
          Invocation.method(#createUpdateProduct, [product, langCode]),
          returnValue:
              Future<_i2.Result<_i6.Product, _i7.ProductsManagerError>>.value(
                  _FakeResult<_i6.Product, _i7.ProductsManagerError>())) as _i5
          .Future<_i2.Result<_i6.Product, _i7.ProductsManagerError>>);
  @override
  _i5.Future<_i2.Result<_i4.ProductWithOCRIngredients, _i7.ProductsManagerError>>
      updateProductAndExtractIngredients(_i6.Product? product, [String? langCode]) =>
          (super.noSuchMethod(
              Invocation.method(
                  #updateProductAndExtractIngredients, [product, langCode]),
              returnValue:
                  Future<_i2.Result<_i4.ProductWithOCRIngredients, _i7.ProductsManagerError>>.value(
                      _FakeResult<_i4.ProductWithOCRIngredients, _i7.ProductsManagerError>())) as _i5
              .Future<_i2.Result<_i4.ProductWithOCRIngredients, _i7.ProductsManagerError>>);
}

/// A class which mocks [Backend].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackend extends _i1.Mock implements _i9.Backend {
  MockBackend() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addObserver(_i9.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#addObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  void removeObserver(_i9.BackendObserver? observer) =>
      super.noSuchMethod(Invocation.method(#removeObserver, [observer]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.Result<_i10.UserParams, _i11.BackendError>> loginOrRegister(
          {String? googleIdToken, String? appleAuthorizationCode}) =>
      (super.noSuchMethod(
              Invocation.method(#loginOrRegister, [], {
                #googleIdToken: googleIdToken,
                #appleAuthorizationCode: appleAuthorizationCode
              }),
              returnValue:
                  Future<_i2.Result<_i10.UserParams, _i11.BackendError>>.value(
                      _FakeResult<_i10.UserParams, _i11.BackendError>()))
          as _i5.Future<_i2.Result<_i10.UserParams, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<bool, _i11.BackendError>> updateUserParams(
          _i10.UserParams? userParams,
          {String? backendClientTokenOverride}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUserParams, [userParams],
                  {#backendClientTokenOverride: backendClientTokenOverride}),
              returnValue: Future<_i2.Result<bool, _i11.BackendError>>.value(
                  _FakeResult<bool, _i11.BackendError>()))
          as _i5.Future<_i2.Result<bool, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i8.BackendProduct?, _i11.BackendError>> requestProduct(
          String? barcode) =>
      (super.noSuchMethod(Invocation.method(#requestProduct, [barcode]),
          returnValue:
              Future<_i2.Result<_i8.BackendProduct?, _i11.BackendError>>.value(
                  _FakeResult<_i8.BackendProduct?, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i8.BackendProduct?, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i2.None, _i11.BackendError>> createUpdateProduct(
          String? barcode,
          {_i12.VegStatus? vegetarianStatus,
          _i12.VegStatus? veganStatus}) =>
      (super.noSuchMethod(
          Invocation.method(#createUpdateProduct, [barcode],
              {#vegetarianStatus: vegetarianStatus, #veganStatus: veganStatus}),
          returnValue: Future<_i2.Result<_i2.None, _i11.BackendError>>.value(
              _FakeResult<_i2.None, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i2.None, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i2.None, _i11.BackendError>> sendReport(
          String? barcode, String? reportText) =>
      (super.noSuchMethod(Invocation.method(#sendReport, [barcode, reportText]),
          returnValue: Future<_i2.Result<_i2.None, _i11.BackendError>>.value(
              _FakeResult<_i2.None, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i2.None, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i2.None, _i11.BackendError>> sendProductScan(
          String? barcode) =>
      (super.noSuchMethod(Invocation.method(#sendProductScan, [barcode]),
          returnValue: Future<_i2.Result<_i2.None, _i11.BackendError>>.value(
              _FakeResult<_i2.None, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i2.None, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i10.UserParams, _i11.BackendError>> userData() =>
      (super.noSuchMethod(Invocation.method(#userData, []),
              returnValue:
                  Future<_i2.Result<_i10.UserParams, _i11.BackendError>>.value(
                      _FakeResult<_i10.UserParams, _i11.BackendError>()))
          as _i5.Future<_i2.Result<_i10.UserParams, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<List<_i13.BackendProductsAtShop>, _i11.BackendError>>
      requestProductsAtShops(Iterable<String>? osmIds) => (super.noSuchMethod(
          Invocation.method(#requestProductsAtShops, [osmIds]),
          returnValue: Future<_i2.Result<List<_i13.BackendProductsAtShop>, _i11.BackendError>>.value(
              _FakeResult<List<_i13.BackendProductsAtShop>,
                  _i11.BackendError>())) as _i5
          .Future<_i2.Result<List<_i13.BackendProductsAtShop>, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<List<_i14.BackendShop>, _i11.BackendError>>
      requestShops(Iterable<String>? osmIds) => (super.noSuchMethod(
          Invocation.method(#requestShops, [osmIds]),
          returnValue: Future<
                  _i2.Result<List<_i14.BackendShop>, _i11.BackendError>>.value(
              _FakeResult<List<_i14.BackendShop>, _i11.BackendError>())) as _i5
          .Future<_i2.Result<List<_i14.BackendShop>, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i2.None, _i11.BackendError>> productPresenceVote(
          String? barcode, String? osmId, bool? positive) =>
      (super.noSuchMethod(
          Invocation.method(#productPresenceVote, [barcode, osmId, positive]),
          returnValue: Future<_i2.Result<_i2.None, _i11.BackendError>>.value(
              _FakeResult<_i2.None, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i2.None, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i2.None, _i11.BackendError>> putProductToShop(
          String? barcode, String? osmId) =>
      (super.noSuchMethod(
          Invocation.method(#putProductToShop, [barcode, osmId]),
          returnValue: Future<_i2.Result<_i2.None, _i11.BackendError>>.value(
              _FakeResult<_i2.None, _i11.BackendError>())) as _i5
          .Future<_i2.Result<_i2.None, _i11.BackendError>>);
  @override
  _i5.Future<_i2.Result<_i14.BackendShop, _i11.BackendError>> createShop(
          {String? name, _i15.Point<double>? coords, String? type}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createShop, [], {#name: name, #coords: coords, #type: type}),
              returnValue:
                  Future<_i2.Result<_i14.BackendShop, _i11.BackendError>>.value(
                      _FakeResult<_i14.BackendShop, _i11.BackendError>()))
          as _i5.Future<_i2.Result<_i14.BackendShop, _i11.BackendError>>);
  @override
  _i5.Future<_i3.BackendResponse> customGet(String? path,
          [Map<String, String>? queryParams, Map<String, String>? headers]) =>
      (super.noSuchMethod(
              Invocation.method(#customGet, [path, queryParams, headers]),
              returnValue:
                  Future<_i3.BackendResponse>.value(_FakeBackendResponse()))
          as _i5.Future<_i3.BackendResponse>);
}
